"""add_optimization_runs

Revision ID: 3d7a5f324ff0
Revises: eb2203bc0709
Create Date: 2024-04-06 18:29:29.854575

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3d7a5f324ff0"
down_revision = "eb2203bc0709"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recommendation", sa.Column("count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendation", "count")
    # ### end Alembic commands ###
